steps:
- name: gcr.io/cloud-builders/docker
  script: >
    docker build -t
    us-docker.pkg.dev/allstar-ossf/allstar-ossf/allstar:latest .
  automapSubstitutions: true
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args: ['-c', 'gcloud app deploy --appyaml=app-staging.yaml --project=allstar-ossf --image-url us-docker.pkg.dev/allstar-ossf/allstar-ossf:latest']
timeout: 1200s
options:
  volumes:
  - name: go-modules
    path: /go
